drop table if exists `mall_store`;
create table `mall_store`
(
    `id`             bigint(20) unsigned not null auto_increment comment '主键',
    `tenant_id`      bigint(20) unsigned not null default 0 comment '租户主键',
    `store_name`     varchar(255)        not null default '' comment '店铺名称',
    `source_name`    varchar(64)         not null default '' comment '数据来源',
    `source_version` varchar(64)         not null default '' comment '来源版本号',
    `created_at`     timestamp           not null default current_timestamp comment '创建时间',
    `creator_id`     bigint(20) unsigned not null default 0 comment '创建人主键',
    `creator_code`   varchar(128)        not null default '' comment '创建人编码',
    `creator_name`   varchar(255)        not null default '' comment '创建人名称',
    `modified_at`    timestamp           not null default current_timestamp on update current_timestamp comment '更新时间',
    `modifier_id`    bigint(20) unsigned not null default 0 comment '更新人主键',
    `modifier_code`  varchar(128)        not null default '' comment '更新人编码',
    `modifier_name`  varchar(255)        not null default '' comment '更新人名称',
    `disabled_at`    timestamp           null     default null comment '禁用时间',
    `disabled_id`    bigint(20) unsigned not null default 0 comment '禁用人主键',
    `disabled_code`  varchar(128)        not null default '' comment '禁用人编码',
    `disabled_name`  varchar(128)        not null default '' comment '禁用人名称',
    `removed_at`     timestamp           null     default null comment '删除时间',
    `remover_id`     bigint(20) unsigned not null default 0 comment '删除人主键',
    `remover_code`   varchar(128)        not null default '' comment '删除人编码',
    `remover_name`   varchar(255)        not null default '' comment '删除人名称',
    primary key (`id`)
) engine = innodb comment '店铺';

drop table if exists `mall_product_type`;
create table `mall_product_type`
(
    `id`             bigint(20) unsigned  not null auto_increment comment '主键',
    `tenant_id`      bigint(20) unsigned  not null default 0 comment '租户主键',
    `store_id`       bigint(20) unsigned  not null default 0 comment '店铺主键',
    `store_name`     varchar(255)         not null default '' comment '店铺名称',
    `parent_id`      bigint(20) unsigned  not null default 0 comment '父级主键',
    `parent_name`    varchar(255)         not null default '' comment '父级名称',
    `type_name`      varchar(255)         not null default '' comment '分类名称',
    `type_icon`      varchar(1024)        not null default '' comment '分类图标',
    `type_sorting`   smallint(5) unsigned not null default 0 comment '分类排序',
    `source_name`    varchar(64)         not null default '' comment '数据来源',
    `source_version` varchar(64)         not null default '' comment '来源版本号',
    `created_at`     timestamp           not null default current_timestamp comment '创建时间',
    `creator_id`     bigint(20) unsigned not null default 0 comment '创建人主键',
    `creator_code`   varchar(128)        not null default '' comment '创建人编码',
    `creator_name`   varchar(255)        not null default '' comment '创建人名称',
    `modified_at`    timestamp           not null default current_timestamp on update current_timestamp comment '更新时间',
    `modifier_id`    bigint(20) unsigned not null default 0 comment '更新人主键',
    `modifier_code`  varchar(128)        not null default '' comment '更新人编码',
    `modifier_name`  varchar(255)        not null default '' comment '更新人名称',
    `disabled_at`    timestamp           null     default null comment '禁用时间',
    `disabled_id`    bigint(20) unsigned not null default 0 comment '禁用人主键',
    `disabled_code`  varchar(128)        not null default '' comment '禁用人编码',
    `disabled_name`  varchar(128)        not null default '' comment '禁用人名称',
    `removed_at`     timestamp           null     default null comment '删除时间',
    `remover_id`     bigint(20) unsigned not null default 0 comment '删除人主键',
    `remover_code`   varchar(128)        not null default '' comment '删除人编码',
    `remover_name`   varchar(255)        not null default '' comment '删除人名称',
    primary key (`id`),
    index `idx_store_id` (`store_id`),
    index `idx_parent_id` (`parent_id`)
) engine = innodb comment '商品分类';
