#drop table if exists `example`;
#create table `example`
#(
#    `id`            bigint(20) unsigned not null auto_increment comment '主键',
#    `tenant_id`     bigint(20) unsigned not null default 0 comment '租户主键',
#    `disabled_at`   timestamp           null     default null comment '禁用时间',
#    `disabled_id`   bigint(20) unsigned not null default 0 comment '禁用人主键',
#    `disabled_code` varchar(64)         not null default '' comment '禁用人编码',
#    `disabled_name` varchar(64)         not null default '' comment '禁用人名称',
#    `created_at`    timestamp           not null default current_timestamp comment '创建时间',
#    `modified_at`   timestamp           not null default current_timestamp on update current_timestamp comment '更新时间',
#    `creator_id`    bigint(20) unsigned not null default 0 comment '创建人主键',
#    `creator_code`  varchar(64)         not null default '' comment '创建人编码',
#    `creator_name`  varchar(255)        not null default '' comment '创建人昵称',
#    `modifier_id`   bigint(20) unsigned not null default 0 comment '更新人主键',
#    `modifier_code` varchar(64)         not null default '' comment '更新人编码',
#    `modifier_name` varchar(255)        not null default '' comment '更新人昵称',
#    `removed_at`    timestamp               null default null comment '删除时间',
#    `remover_id`    bigint(20) unsigned not null default 0 comment '删除人主键',
#    `remover_code`  varchar(64)         not null default '' comment '删除人编码',
#    `remover_name`  varchar(255)        not null default '' comment '删除人昵称',
#    primary key (`id`)
#) engine = innodb comment '建表示例';

drop table if exists `address_map_result`;
create table `address_map_result`
(
    `id`                  bigint(20) unsigned not null auto_increment comment '主键',
    `tenant_id`           bigint(20) unsigned not null default 0 comment '租户主键',
    `origin_address`      varchar(512)       not null default '' comment '原地址',
    `origin_address_hash` bigint(20) unsigned not null default 0 comment '原地址CRC32值',
    `gaode_province`      varchar(255)        not null default '' comment '高德省份',
    `gaode_city`          varchar(255)        not null default '' comment '高德城市',
    `gaode_district`      varchar(255)        not null default '' comment '高德区划',
    `gaode_street`        varchar(255)        not null default '' comment '高德街道',
    `gaode_address`       varchar(255)        not null default '' comment '高德地址',
    `gaode_address_lng`   decimal(10, 7)      null     default null comment '高德地址经度',
    `gaode_address_lat`   decimal(10, 7)      null     default null comment '高德地址纬度',
    `tengxun_province`    varchar(255)        not null default '' comment '腾讯省份',
    `tengxun_city`        varchar(255)        not null default '' comment '腾讯城市',
    `tengxun_district`    varchar(255)        not null default '' comment '腾讯区划',
    `tengxun_street`      varchar(255)        not null default '' comment '腾讯街道',
    `tengxun_address`     varchar(255)        not null default '' comment '腾讯地址',
    `tengxun_address_lng` decimal(10, 7)      null     default null comment '腾讯地址经度',
    `tengxun_address_lat` decimal(10, 7)      null     default null comment '腾讯地址纬度',
    `baidu_province`      varchar(255)        not null default '' comment '百度省份',
    `baidu_city`          varchar(255)        not null default '' comment '百度城市',
    `baidu_district`      varchar(255)        not null default '' comment '百度区划',
    `baidu_street`        varchar(255)        not null default '' comment '百度街道',
    `baidu_address`       varchar(255)        not null default '' comment '百度地址',
    `baidu_address_lng`   decimal(10, 7)      null     default null comment '百度地址经度',
    `baidu_address_lat`   decimal(10, 7)      null     default null comment '百度地址纬度',
    `disabled_at`         timestamp           null     default null comment '禁用时间',
    `disabled_id`         bigint(20) unsigned not null default 0 comment '禁用人主键',
    `disabled_code`       varchar(64)         not null default '' comment '禁用人编码',
    `disabled_name`       varchar(64)         not null default '' comment '禁用人名称',
    `created_at`          timestamp           not null default current_timestamp comment '创建时间',
    `modified_at`         timestamp           not null default current_timestamp on update current_timestamp comment '更新时间',
    `creator_id`          bigint(20) unsigned not null default 0 comment '创建人主键',
    `creator_code`        varchar(64)         not null default '' comment '创建人编码',
    `creator_name`        varchar(255)        not null default '' comment '创建人昵称',
    `modifier_id`         bigint(20) unsigned not null default 0 comment '更新人主键',
    `modifier_code`       varchar(64)         not null default '' comment '更新人编码',
    `modifier_name`       varchar(255)        not null default '' comment '更新人昵称',
    `removed_at`          timestamp           null     default null comment '删除时间',
    `remover_id`          bigint(20) unsigned not null default 0 comment '删除人主键',
    `remover_code`        varchar(64)         not null default '' comment '删除人编码',
    `remover_name`        varchar(255)        not null default '' comment '删除人昵称',
    primary key (`id`),
    index `idx_origin_address` (`origin_address`, `origin_address_hash`)
) engine = innodb comment '图商解析结果';
