drop table if exists `pay_order`;
create table `pay_order`
(
    `id`             bigint(20) unsigned not null auto_increment comment '主键',
    `tenant_id`      bigint(20) unsigned not null default 0 comment '租户主键',
    `user_id`        bigint(20) unsigned not null default 0 comment '用户主键',
    `user_name`      varchar(255)        not null default '' comment '用户名称',
    `pay_desc`       varchar(255)        not null default '' comment '订单描述',
    `pay_type`       varchar(32)         not null default '' comment '支付方式',
    `pay_amount`     decimal(10, 3)      null     default null comment '支付金额',
    `refund_amount`  decimal(10, 3)      null     default null comment '退款金额',
    `prepay_id`      varchar(128)        not null default '' comment '预支付标识',
    `sign_type`      varchar(32)         not null default '' comment '签名方式',
    `sign_timestamp` varchar(64)         not null default '' comment '签名时间戳',
    `sign_nonce`     varchar(255)        not null default '' comment '签名随机字符串',
    `callback_bean`  varchar(128)        not null default '' comment '回调Bean',
    `callback_url`   varchar(1024)       not null default '' comment '回调地址',
    `callback_id`    bigint(20) unsigned not null default 0 comment '回调主键',
    `merged_id`       bigint(20) unsigned not null default 0 comment '合并主键',
    `completed_at`   timestamp           null     default null comment '完成支付时间',
    `source_name`    varchar(64)         not null default '' comment '数据来源',
    `source_version` varchar(64)         not null default '' comment '来源版本号',
    `created_at`     timestamp           not null default current_timestamp comment '创建时间',
    `creator_id`     bigint(20) unsigned not null default 0 comment '创建人主键',
    `creator_code`   varchar(128)        not null default '' comment '创建人编码',
    `creator_name`   varchar(255)        not null default '' comment '创建人名称',
    `modified_at`    timestamp           not null default current_timestamp on update current_timestamp comment '更新时间',
    `modifier_id`    bigint(20) unsigned not null default 0 comment '更新人主键',
    `modifier_code`  varchar(128)        not null default '' comment '更新人编码',
    `modifier_name`  varchar(255)        not null default '' comment '更新人名称',
    `disabled_at`    timestamp           null     default null comment '禁用时间',
    `disabled_id`    bigint(20) unsigned not null default 0 comment '禁用人主键',
    `disabled_code`  varchar(128)        not null default '' comment '禁用人编码',
    `disabled_name`  varchar(128)        not null default '' comment '禁用人名称',
    `removed_at`     timestamp           null     default null comment '删除时间',
    `remover_id`     bigint(20) unsigned not null default 0 comment '删除人主键',
    `remover_code`   varchar(128)        not null default '' comment '删除人编码',
    `remover_name`   varchar(255)        not null default '' comment '删除人名称',
    primary key (`id`),
    index `idx_user_id` (`user_id`),
    index `idx_merged_id` (`merged_id`)
) engine = innodb comment '支付订单';