drop table if exists `user_user`;
create table `user_user`
(
    `id`             bigint(20) unsigned not null auto_increment comment '主键',
    `tenant_id`      bigint(20) unsigned not null default 0 comment '租户主键',
    `invited_uid`    bigint(20) unsigned not null default 0 comment '邀请人主键',
    `invited_pid`    bigint(20) unsigned not null default 0 comment '父级邀请人主键',
    `wx_unionid`     varchar(255)        not null default '' comment '微信unionid',
    `wx_openid_ggh`  varchar(255)        not null default '' comment '微信公众号openid',
    `wx_openid_xcx`  varchar(255)        not null default '' comment '微信小程序openid',
    `user_code`      varchar(64)         not null default '' comment '编码',
    `user_name`      varchar(255)        not null default '' comment '名称',
    `user_avatar`    varchar(1024)       not null default '' comment '头像链接',
    `login_username` varchar(255)        not null default '' comment '登录账号',
    `login_password` varchar(255)        not null default '' comment '登录密码',
    `contact_phone`  varchar(255)        not null default '' comment '联系电话',
    `contact_email`  varchar(255)        not null default '' comment '邮箱地址',
    `source_name`    varchar(64)         not null default '' comment '数据来源',
    `source_version` varchar(64)         not null default '' comment '来源版本号',
    `created_at`     timestamp           not null default current_timestamp comment '创建时间',
    `creator_id`     bigint(20) unsigned not null default 0 comment '创建人主键',
    `creator_code`   varchar(128)        not null default '' comment '创建人编码',
    `creator_name`   varchar(255)        not null default '' comment '创建人名称',
    `modified_at`    timestamp           not null default current_timestamp on update current_timestamp comment '更新时间',
    `modifier_id`    bigint(20) unsigned not null default 0 comment '更新人主键',
    `modifier_code`  varchar(128)        not null default '' comment '更新人编码',
    `modifier_name`  varchar(255)        not null default '' comment '更新人名称',
    `disabled_at`    timestamp           null     default null comment '禁用时间',
    `disabled_id`    bigint(20) unsigned not null default 0 comment '禁用人主键',
    `disabled_code`  varchar(128)        not null default '' comment '禁用人编码',
    `disabled_name`  varchar(128)        not null default '' comment '禁用人名称',
    `removed_at`     timestamp           null     default null comment '删除时间',
    `remover_id`     bigint(20) unsigned not null default 0 comment '删除人主键',
    `remover_code`   varchar(128)        not null default '' comment '删除人编码',
    `remover_name`   varchar(255)        not null default '' comment '删除人名称',
    primary key (`id`),
    index `idx_wx_openid_ggh` (`wx_openid_ggh`, `wx_unionid`),
    index `idx_wx_openid_xcx` (`wx_openid_xcx`, `wx_unionid`),
    index `idx_login_username` (`login_username`),
    index `idx_contact_phone` (`contact_phone`)
) engine = innodb comment '用户';
