server:
  port: 8100
  shutdown: GRACEFUL

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: @project.parent.artifactId@
  profiles:
    active: @pom.profile.name@
  cache:
    type: REDIS
  data:
    redis:
      database: 1
      host: @pom.redis.ip@
      port: @pom.redis.port@
      password: @pom.redis.password@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://@pom.mysql.ip@:@pom.mysql.port@/@project.parent.artifactId@-@pom.profile.name@
    username: @pom.mysql.username@
    password: @pom.mysql.password@
  flyway:
    enabled: true
    baseline-on-migrate: false
    encoding: UTF-8
    locations: classpath:migration
    sql-migration-prefix: V
    sql-migration-separator: _
    sql-migration-suffixes: .sql
    validate-on-migrate: false
    clean-disabled: false
  cloud:
    nacos:
      discovery:
        server-addr: @pom.nacos.addresses@
        namespace: @pom.nacos.namespace@
      config:
        server-addr: @pom.nacos.addresses@
        namespace: @pom.nacos.namespace@
        file-extension: yml
        enabled: true
        refresh-enabled: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.beicroon.service.*.model

#rocketmq:
#  nameServer: @pom.mq.address@
#  namespace: @pom.profile.name@
#  groupId: @project.parent.artifactId@

xxl:
  job:
    admin:
      addresses: @pom.job.addresses@