drop table if exists `user_account`;
create table `user_account`
(
    `id`              bigint(20) unsigned not null auto_increment comment '主键',
    `tenant_id`       bigint(20) unsigned not null default 0 comment '租户主键',
    `wx_unionid`      varchar(255)        not null default '' comment '微信unionid',
    `wx_openid_ggh`   varchar(255)        not null default '' comment '微信公众号openid',
    `wx_openid_xcx`   varchar(255)        not null default '' comment '微信小程序openid',
    `code`            varchar(64)         not null default '' comment '编码',
    `name`            varchar(255)        not null default '' comment '名称',
    `username`        varchar(255)        not null default '' comment '登录账号',
    `password`        varchar(255)        not null default '' comment '登录密码',
    `phone`           varchar(255)        not null default '' comment '联系电话',
    `email`           varchar(255)        not null default '' comment '邮箱地址',
    `avatar`          varchar(1024)       not null default '' comment '头像链接',
    `role`            varchar(32)         not null default '' comment '角色',
    `balance`         decimal(10, 3)      not null default 0 comment '余额',
    `recharge_amount` decimal(10, 3)      not null default 0 comment '累计充值金额',
    `bonus_amount`    decimal(10, 3)      not null default 0 comment '累计赠送金额',
    `expensed_amount` decimal(10, 3)      not null default 0 comment '累计消费金额',
    `created_at`      timestamp           not null default current_timestamp comment '创建时间',
    `creator_id`      bigint(20) unsigned not null default 0 comment '创建人主键',
    `creator_code`    varchar(128)        not null default '' comment '创建人编码',
    `creator_name`    varchar(255)        not null default '' comment '创建人昵称',
    `modified_at`     timestamp           not null default current_timestamp on update current_timestamp comment '更新时间',
    `modifier_id`     bigint(20) unsigned not null default 0 comment '更新人主键',
    `modifier_code`   varchar(128)        not null default '' comment '更新人编码',
    `modifier_name`   varchar(255)        not null default '' comment '更新人昵称',
    `disabled_at`     timestamp           null     default null comment '禁用时间',
    `disabled_id`     bigint(20) unsigned not null default 0 comment '禁用人主键',
    `disabled_code`   varchar(128)        not null default '' comment '禁用人编码',
    `disabled_name`   varchar(128)        not null default '' comment '禁用人名称',
    `removed_at`      timestamp           null     default null comment '删除时间',
    `remover_id`      bigint(20) unsigned not null default 0 comment '删除人主键',
    `remover_code`    varchar(128)        not null default '' comment '删除人编码',
    `remover_name`    varchar(255)        not null default '' comment '删除人昵称',
    primary key (`id`),
    index `idx_wx_unionid` (`wx_unionid`),
    index `idx_wx_openid_ggh` (`wx_openid_ggh`),
    index `idx_wx_openid_xcx` (`wx_openid_xcx`),
    index `idx_username` (`username`),
    index `idx_phone` (`phone`)
) engine = innodb comment '用户';

drop table if exists `user_account_balance_relation`;
create table `user_account_balance_relation`
(
    `id`            bigint(20) unsigned not null auto_increment comment '主键',
    `tenant_id`     bigint(20) unsigned not null default 0 comment '租户主键',
    `account_id`    bigint(20) unsigned not null default 0 comment '账号主键',
    `type`          varchar(64)         not null default '' comment '类型(收入/支出)',
    `kind`          varchar(64)         not null default '' comment '种类(充值/赠送/消费/分红)',
    `amount`        decimal(10, 3)      not null default 0 comment '金额',
    `balance`       decimal(10, 3)      not null default 0 comment '余额',
    `remark`        varchar(512)        not null default '' comment '备注',
    `created_at`    timestamp           not null default current_timestamp comment '创建时间',
    `creator_id`    bigint(20) unsigned not null default 0 comment '创建人主键',
    `creator_code`  varchar(128)        not null default '' comment '创建人编码',
    `creator_name`  varchar(255)        not null default '' comment '创建人昵称',
    `modified_at`   timestamp           not null default current_timestamp on update current_timestamp comment '更新时间',
    `modifier_id`   bigint(20) unsigned not null default 0 comment '更新人主键',
    `modifier_code` varchar(128)        not null default '' comment '更新人编码',
    `modifier_name` varchar(255)        not null default '' comment '更新人昵称',
    primary key (`id`),
    index `idx_account_id` (`account_id`, `type`),
    index `idx_type` (`type`)
) engine = innodb comment '用户余额';
