drop table if exists `ronmio_customer`;
create table `ronmio_customer`
(
    `id`            bigint(20) unsigned not null auto_increment comment '主键',
    `tenant_id`     bigint(20) unsigned not null default 0 comment '租户主键',
    `name`          varchar(255)        not null default '' comment '客户名称',
    `phone`         varchar(255)        not null default '' comment '联系电话',
    `created_at`    timestamp           not null default current_timestamp comment '创建时间',
    `creator_id`    bigint(20) unsigned not null default 0 comment '创建人主键',
    `creator_code`  varchar(128)        not null default '' comment '创建人编码',
    `creator_name`  varchar(255)        not null default '' comment '创建人昵称',
    `modified_at`   timestamp           not null default current_timestamp on update current_timestamp comment '更新时间',
    `modifier_id`   bigint(20) unsigned not null default 0 comment '更新人主键',
    `modifier_code` varchar(128)        not null default '' comment '更新人编码',
    `modifier_name` varchar(255)        not null default '' comment '更新人昵称',
    `disabled_at`   timestamp           null     default null comment '禁用时间',
    `disabled_id`   bigint(20) unsigned not null default 0 comment '禁用人主键',
    `disabled_code` varchar(128)        not null default '' comment '禁用人编码',
    `disabled_name` varchar(128)        not null default '' comment '禁用人名称',
    `removed_at`    timestamp           null     default null comment '删除时间',
    `remover_id`    bigint(20) unsigned not null default 0 comment '删除人主键',
    `remover_code`  varchar(128)        not null default '' comment '删除人编码',
    `remover_name`  varchar(255)        not null default '' comment '删除人昵称',
    primary key (`id`)
) engine = innodb comment '客户';

drop table if exists `ronmio_packing_list_invoice`;
create table `ronmio_packing_list_invoice`
(
    `id`                       bigint(20) unsigned     not null auto_increment comment '主键',
    `tenant_id`                bigint(20) unsigned     not null default 0 comment '租户主键',
    `code`                     varchar(128)            not null default '' comment '箱单单号',
    `customer_id`              bigint(20) unsigned     not null default 0 comment '客户主键',
    `customer_name`            varchar(255)            not null default '' comment '客户名称',
    `train_code`               varchar(128)            not null default '' comment '班列号',
    `container_code`           varchar(128)            not null default '' comment '货柜号',
    `seller_name`              varchar(255)            not null default '' comment '卖方名称',
    `seller_addr`              varchar(255)            not null default '' comment '卖方地址',
    `buyer_name`               varchar(255)            not null default '' comment '买方名称',
    `buyer_addr`               varchar(255)            not null default '' comment '买方地址',
    `contract_code`            varchar(255)            not null default '' comment '合同号',
    `origin_country`           varchar(255)            not null default '' comment '原产国',
    `price_term`               varchar(255)            not null default '' comment '价格条款',
    `box_type`                 varchar(64)             not null default '' comment '箱型',
    `total_amount`             decimal(10, 3) unsigned not null default 0 comment '总金额',
    `total_volume`             decimal(10, 3) unsigned not null default 0 comment '总体积',
    `total_net_weight`         decimal(10, 3) unsigned not null default 0 comment '总净重',
    `total_gross_weight`       decimal(10, 3) unsigned not null default 0 comment '总毛重',
    `remark`                   varchar(255)            not null default '' comment '备注',
    `total_amount_calculation` varchar(64)             not null default '' comment '总价计算方式',
    `net_weight_fractional`    varchar(64)             not null default '' comment '净重小数位数',
    `gross_weight_fractional`  varchar(64)             not null default '' comment '毛重小数位数',
    `created_at`               timestamp               not null default current_timestamp comment '创建时间',
    `creator_id`               bigint(20) unsigned     not null default 0 comment '创建人主键',
    `creator_code`             varchar(128)            not null default '' comment '创建人编码',
    `creator_name`             varchar(255)            not null default '' comment '创建人昵称',
    `modified_at`              timestamp               not null default current_timestamp on update current_timestamp comment '更新时间',
    `modifier_id`              bigint(20) unsigned     not null default 0 comment '更新人主键',
    `modifier_code`            varchar(128)            not null default '' comment '更新人编码',
    `modifier_name`            varchar(255)            not null default '' comment '更新人昵称',
    `removed_at`               timestamp               null     default null comment '删除时间',
    `remover_id`               bigint(20) unsigned     not null default 0 comment '删除人主键',
    `remover_code`             varchar(128)            not null default '' comment '删除人编码',
    `remover_name`             varchar(255)            not null default '' comment '删除人昵称',
    primary key (`id`),
    index `idx_code` (`code`),
    index `idx_customer_id` (`customer_id`),
    index `idx_train_code` (`train_code`)
) engine = innodb comment '箱单发票';

drop table if exists `ronmio_packing_list_invoice_container_relation`;
create table `ronmio_packing_list_invoice_container_relation`
(
    `id`                        bigint(20) unsigned     not null auto_increment comment '主键',
    `tenant_id`                 bigint(20) unsigned     not null default 0 comment '租户主键',
    `packing_list_invoice_id`   bigint(20) unsigned     not null default 0 comment '箱单发票主键',
    `packing_list_invoice_code` varchar(128)            not null default '' comment '箱单发票单号',
    `code`                      varchar(128)            not null default '' comment '箱号',
    `count`                     decimal(11, 3) unsigned not null default 0 comment '件数',
    `volume`                    decimal(11, 3) unsigned not null default 0 comment '体积(m³)',
    `net_weight`                decimal(11, 3) unsigned not null default 0 comment '净重(kg)',
    `gross_weight`              decimal(11, 3) unsigned not null default 0 comment '毛重(kg)',
    `created_at`                timestamp               not null default current_timestamp comment '创建时间',
    `creator_id`                bigint(20) unsigned     not null default 0 comment '创建人主键',
    `creator_code`              varchar(128)            not null default '' comment '创建人编码',
    `creator_name`              varchar(255)            not null default '' comment '创建人昵称',
    `modified_at`               timestamp               not null default current_timestamp on update current_timestamp comment '更新时间',
    `modifier_id`               bigint(20) unsigned     not null default 0 comment '更新人主键',
    `modifier_code`             varchar(128)            not null default '' comment '更新人编码',
    `modifier_name`             varchar(255)            not null default '' comment '更新人昵称',
    `removed_at`                timestamp               null     default null comment '删除时间',
    `remover_id`                bigint(20) unsigned     not null default 0 comment '删除人主键',
    `remover_code`              varchar(128)            not null default '' comment '删除人编码',
    `remover_name`              varchar(255)            not null default '' comment '删除人昵称',
    primary key (`id`),
    index `idx_packing_list_invoice_id` (`packing_list_invoice_id`),
    index `idx_packing_list_invoice_code` (`packing_list_invoice_code`),
    index `idx_code` (`code`)
) engine = innodb comment '箱单';

drop table if exists `ronmio_packing_list_invoice_record_relation`;
create table `ronmio_packing_list_invoice_record_relation`
(
    `id`                        bigint(20) unsigned     not null auto_increment comment '主键',
    `tenant_id`                 bigint(20) unsigned     not null default 0 comment '租户主键',
    `packing_list_invoice_id`   bigint(20) unsigned     not null default 0 comment '箱单发票主键',
    `packing_list_invoice_code` varchar(128)            not null default '' comment '箱单发票单号',
    `container_id`              bigint(20) unsigned     not null default 0 comment '箱单主键',
    `container_code`            varchar(128)            not null default '' comment '箱号',
    `receive_name`              varchar(255)            not null default '' comment '收货人',
    `level`                     varchar(64)             not null default '' comment '等级',
    `thickness`                 smallint(5) unsigned    not null default 0 comment '厚度(mm)',
    `width`                     smallint(5) unsigned    not null default 0 comment '宽度(mm)',
    `length`                    smallint(5) unsigned    not null default 0 comment '长度(mm)',
    `commodity_name`            varchar(255)            not null default '' comment '商品名称',
    `commodity_code`            varchar(255)            not null default '' comment '商品编码',
    `count`                     decimal(11, 3) unsigned not null default 0 comment '件数',
    `volume`                    decimal(11, 3) unsigned not null default 0 comment '体积(m³)',
    `net_weight`                decimal(11, 3) unsigned not null default 0 comment '净重(kg)',
    `gross_weight`              decimal(11, 3) unsigned not null default 0 comment '毛重(kg)',
    `unit_price`                decimal(11, 3) unsigned not null default 0 comment '单价(元)',
    `total_amount`              decimal(11, 3) unsigned not null default 0 comment '总金额(元)',
    `destination`               varchar(255)            not null default '' comment '目的地',
    `remark`                    varchar(255)            not null default '' comment '备注',
    `created_at`                timestamp               not null default current_timestamp comment '创建时间',
    `creator_id`                bigint(20) unsigned     not null default 0 comment '创建人主键',
    `creator_code`              varchar(128)            not null default '' comment '创建人编码',
    `creator_name`              varchar(255)            not null default '' comment '创建人昵称',
    `modified_at`               timestamp               not null default current_timestamp on update current_timestamp comment '更新时间',
    `modifier_id`               bigint(20) unsigned     not null default 0 comment '更新人主键',
    `modifier_code`             varchar(128)            not null default '' comment '更新人编码',
    `modifier_name`             varchar(255)            not null default '' comment '更新人昵称',
    `removed_at`                timestamp               null     default null comment '删除时间',
    `remover_id`                bigint(20) unsigned     not null default 0 comment '删除人主键',
    `remover_code`              varchar(128)            not null default '' comment '删除人编码',
    `remover_name`              varchar(255)            not null default '' comment '删除人昵称',
    primary key (`id`),
    index `idx_packing_list_invoice_id` (`packing_list_invoice_id`),
    index `idx_packing_list_invoice_code` (`packing_list_invoice_code`),
    index `idx_container_id` (`container_id`),
    index `idx_container_code` (`container_code`),
    index `idx_specification` (`level`, `thickness`, `width`, `length`)
) engine = innodb comment '码单';

drop table if exists `ronmio_packing_list_invoice_price_relation`;
create table `ronmio_packing_list_invoice_price_relation`
(
    `id`                        bigint(20) unsigned     not null auto_increment comment '主键',
    `tenant_id`                 bigint(20) unsigned     not null default 0 comment '租户主键',
    `packing_list_invoice_id`   bigint(20) unsigned     not null default 0 comment '箱单发票主键',
    `packing_list_invoice_code` varchar(128)            not null default '' comment '箱单发票单号',
    `level`                     varchar(64)             not null default '' comment '等级',
    `thickness`                 smallint(5) unsigned    not null default 0 comment '厚度(mm)',
    `width`                     smallint(5) unsigned    not null default 0 comment '宽度(mm)',
    `min_length`                    smallint(5) unsigned    not null default 0 comment '最小长度(mm)',
    `max_length`                    smallint(5) unsigned    not null default 0 comment '最大长度(mm)',
    `unit_price`                decimal(11, 3) unsigned not null default 0 comment '单价(元)',
    `created_at`                timestamp               not null default current_timestamp comment '创建时间',
    `creator_id`                bigint(20) unsigned     not null default 0 comment '创建人主键',
    `creator_code`              varchar(128)            not null default '' comment '创建人编码',
    `creator_name`              varchar(255)            not null default '' comment '创建人昵称',
    `modified_at`               timestamp               not null default current_timestamp on update current_timestamp comment '更新时间',
    `modifier_id`               bigint(20) unsigned     not null default 0 comment '更新人主键',
    `modifier_code`             varchar(128)            not null default '' comment '更新人编码',
    `modifier_name`             varchar(255)            not null default '' comment '更新人昵称',
    `removed_at`                timestamp               null     default null comment '删除时间',
    `remover_id`                bigint(20) unsigned     not null default 0 comment '删除人主键',
    `remover_code`              varchar(128)            not null default '' comment '删除人编码',
    `remover_name`              varchar(255)            not null default '' comment '删除人昵称',
    primary key (`id`),
    index `idx_packing_list_invoice_id` (`packing_list_invoice_id`),
    index `idx_packing_list_invoice_code` (`packing_list_invoice_code`)
) engine = innodb comment '单价';