import {App} from "vue";
import BeicroonButton from "@c/BeicroonButton.vue";
import BeicroonButtonGroup from "@c/BeicroonButtonGroup.vue";
import BeicroonCheckbox from "@c/BeicroonCheckbox.vue";
import BeicroonCheckboxTree from "@c/BeicroonCheckboxTree.vue";
import BeicroonForm from "@c/BeicroonForm.vue";
import BeicroonFormGroup from "@c/BeicroonFormGroup.vue";
import BeicroonFormLoading from "@c/BeicroonFormLoading.vue";
import BeicroonGroup from "@c/BeicroonGroup.vue";
import BeicroonInput from "@c/BeicroonInput.vue";
import BeicroonLoading from "@c/BeicroonLoading.vue";
import BeicroonModule from "@c/BeicroonModule.vue";
import BeicroonPaginator from "@c/BeicroonPaginator.vue";
import BeicroonSearch from "@c/BeicroonSearch.vue";
import BeicroonSelect from "@c/BeicroonSelect.vue";
import BeicroonTable from "@c/BeicroonTable.vue";
import BeicroonTableCell from "@c/BeicroonTableCell.vue";
import BeicroonTableColumn from "@c/BeicroonTableColumn.vue";
import BeicroonTableColumnCell from "@c/BeicroonTableColumnCell.vue";
import BeicroonTableField from "@c/BeicroonTableField.vue";
import BeicroonTableFieldGroup from "@c/BeicroonTableFieldGroup.vue";
import BeicroonTableGroup from "@c/BeicroonTableGroup.vue";
import BeicroonTableView from "@c/BeicroonTableView.vue";

const componentRegister = (app: App) => {
    app.component("BeicroonButton", BeicroonButton);
    app.component("BeicroonButtonGroup", BeicroonButtonGroup);
    app.component("BeicroonCheckbox", BeicroonCheckbox);
    app.component("BeicroonCheckboxTree", BeicroonCheckboxTree);
    app.component("BeicroonForm", BeicroonForm);
    app.component("BeicroonFormGroup", BeicroonFormGroup);
    app.component("BeicroonFormLoading", BeicroonFormLoading);
    app.component("BeicroonGroup", BeicroonGroup);
    app.component("BeicroonInput", BeicroonInput);
    app.component("BeicroonLoading", BeicroonLoading);
    app.component("BeicroonModule", BeicroonModule);
    app.component("BeicroonPaginator", BeicroonPaginator);
    app.component("BeicroonSearch", BeicroonSearch);
    app.component("BeicroonSelect", BeicroonSelect);
    app.component("BeicroonTable", BeicroonTable);
    app.component("BeicroonTableCell", BeicroonTableCell);
    app.component("BeicroonTableColumn", BeicroonTableColumn);
    app.component("BeicroonTableColumnCell", BeicroonTableColumnCell);
    app.component("BeicroonTableField", BeicroonTableField);
    app.component("BeicroonTableFieldGroup", BeicroonTableFieldGroup);
    app.component("BeicroonTableGroup", BeicroonTableGroup);
    app.component("BeicroonTableView", BeicroonTableView);
};

export default componentRegister;
